app/__init__.py, app/config/__init__.py, helm_deploy/laa-access-civil-legal-aid/templates/_helpers.tpl, helm_deploy/laa-access-civil-legal-aid/values/values-dev.yaml
Adds the `CLA_ENVIRONMENT` variable to Config and Sentry.
This environment variable is defined from the values file in the Helm chart.
=> LGA-3206: Add environment parameter to Sentry

.github/workflows/scan-image.yml, .github/workflows/trivy-cron.yml, .github/workflows/trivy-image-scan.yml
Use a cron job to update the trivy vulnerability db.
This sets up a cron job to regularly update the cache in the default branch. This allows subsequent scans to use the cached DB without downloading it again
Based on https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#updating-caches-in-the-default-branch
=> LGA-3336 - Use a cron job to update the trivy vulnerability db

app/templates/categories/domestic_abuse/landing.html, app/templates/categories/housing/landing.html
Fixes a deviation from the content record where "More problems" was erroneously named "Other problems" on two category landing pages.
=> Fix: Rename other problems to more problems

app/categories/__init__.py, app/categories/benefits/__init__.py, app/categories/benefits/forms.py, app/categories/benefits/urls.py, app/categories/views.py, app/templates/categories/benefits/appeal.html, app/templates/categories/index.html, tests/functional_tests/categories/benefits/test_asylum_immigration.py
=> LGA-3391 - Add benefits appeal category

app/categories/__init__.py, app/categories/send/__init__.py, app/categories/send/urls.py, app/templates/categories/index.html, app/templates/categories/send/landing.html, tests/functional_tests/categories/send/test_send.py
=> LGA-3403 - Add SEND category

app/categories/discrimination/forms.py, app/categories/views.py, app/categories/widgets.py, tests/functional_tests/categories/discrimination/test_discrimination.py
- Updates the discrimination where form to allow for multiple selections.
=> LGA-3344: Where did the discrimination occur form

app/static/src/images/action-link-arrow--simple.svg, package.json
- Builds custom images by copying files found in `src/images` to `dist/images`.
- Adds the new arrow icon image
=> LGA-3368: Include custom images

app/static/src/scss/exit_this_page.scss, app/static/src/scss/styles.scss, app/templates/categories/components/cannot-find-your-problem.html, app/templates/categories/index.html, app/templates/categories/more-problems.html
Updates the front door, cannot find your problem and exit this page components to match latest UI design
=> Fix: Front page design

app/means_test/forms/__init__.py, app/means_test/widgets.py
Add logic to make fields conditional using govuk-frontend conditional logic
In your template do: `{{ form.render_conditional(form.field, form.sub_field, conditional_value) }}`
=> Add logic to make fields conditional using govuk-frontend conditional logic

app/means_test/fields.py, app/means_test/money_interval.py, app/means_test/validators.py, tests/unit_tests/means_test/test_money_interval.py
Add new MoneyInterval helper class
Make MoneyField.data return the MoneyInterval.to_json because flask will not be able to serialise a MoneyInterval object This means that MoneyInterval.to_json can be used as payload to send to the backend for any MoneyField fields
=> Add new MoneyInterval helper class

app/means_test/fields.py, app/templates/means_test/components/money-field.html
- Fixes Money Field hint text
- Gives the Money Field the correct ID so it can be scrolled to when clicking an error message
=> Fix Money field hint text

.pre-commit-config.yaml, app/means_test/fields.py, app/means_test/forms/about_you.py, tests/unit_tests/means_test/test_money_field.py
Create a custom IntegerField that allows None as a formdata value
Without this `wtforms.IntegerField.process_formdata` will raise an exception when some conditional fields like `number of children` don't have a default value as it tries to convert a None to an integer.
=> Create a custom IntegerField that allows None as a formdata value

app/means_test/api.py, app/means_test/fields.py, app/means_test/money_interval.py, app/means_test/validators.py
Allows for the moneyfield to be set to 0 and 'please select' if you have no values to input.
=> Update MoneyField handling of 0

app/templates/categories/send/landing.html
- Removes erroneous bracket from SEND Category Landing Page
=> LGA-3403: Fix Special Educational Needs and Disability CLP

app/categories/send/forms.py, app/categories/send/urls.py, tests/functional_tests/categories/send/test_send.py
- Removes 'Are you under 18' web form from SEND routing as this question is not part of the routing.
=> LGA-3558: Child in care routing

app/categories/discrimination/forms.py, app/categories/validators.py, app/categories/widgets.py, tests/functional_tests/categories/discrimination/test_discrimination.py, tests/unit_tests/categories/test_validators.py
- Add optional exclusive checkbox behaviour (See attached recording)
- - This means that when you select another option, then "None of the above" your other selection becomes unchecked
- Add exclusive value validator
- Add functionality test for exclusive value
https://github.com/user-attachments/assets/6c0942cf-6971-4fc8-8294-f0cb3e65b1db
=> LGA 5325: Why were you treated differently

app/main/routes.py, tests/functional_tests/test_entry_points.py, tests/unit_tests/test_entry_points.py, tests/unit_tests/test_locale.py
- Adds the `/start` and `/bsl-start` routes, which are the entry points into the service from [https://www.gov.uk/check-legal-aid](https://www.gov.uk/check-legal-aid)
- These routes support the optional `?local=cy_GB` query string, which sets the users language when included.
=> LGA 3553: Re-create GOV.UK Endpoints

app/__init__.py, app/config/__init__.py, helm_deploy/laa-access-civil-legal-aid/values.yaml
- Makes the rate limiter dependent on the `RATELIMIT_ENABLED` envvar, which can be set via a configmap.
=> Make rate limiter optional

.github/workflows/static-analysis.yml
- Updates the Sonar Cloud action to use the new SonarQube action.
- - The Sonar Cloud action is depreciated, please see: [https://github.com/SonarSource/sonarcloud-github-action](https://github.com/SonarSource/sonarcloud-github-action)
The SonarQube action is a drop-in replacement for the action.
Without this change our pipelines are subject to brownouts and will eventually stop working, please see [here](https://github.com/ministryofjustice/laa-access-civil-legal-aid/actions/runs/13400558033/job/37430326619) for an example of a failed job due to a brownout.
=> Update SonarCloud action to use new SonarQube action

app/categories/urls.py, app/config/__init__.py, app/main/routes.py, app/templates/base.html, app/templates/main/session_expired.html, tests/functional_tests/conftest.py, tests/functional_tests/test_header.py, tests/unit_tests/test_filters.py, tests/unit_tests/test_pages.py
- The header URL and `"/"` endpoint redirects to the GOV.UK service start page on production, and clears the users session
- The users session is no longer cleared by the category landing page
- The GOV.UK link in the header directs to the GOV.UK homepage
- The category landing page now exists at `/find-your-problem` as intended
=> Header redirect to GOV.UK

app/categories/asylum_immigration/urls.py, app/categories/benefits/urls.py, app/categories/community_care/urls.py, app/categories/family/urls.py, app/categories/mental_capacity/urls.py, app/categories/public/urls.py
- Updates category URLs to match those found in the "Access URLs" record: [https://docs.google.com/spreadsheets/d/1KIxjCa0gmEkke7Lwlk_BEFy8m1KQGKIG-kzKZ602ohw](https://docs.google.com/spreadsheets/d/1KIxjCa0gmEkke7Lwlk_BEFy8m1KQGKIG-kzKZ602ohw)
=> Fix incorrect URLs

app/categories/constants.py, app/categories/discrimination/urls.py, app/categories/models.py, app/categories/urls.py, app/categories/views.py, app/means_test/views.py, app/session.py, tests/functional_tests/means_test/test_review.py, tests/unit_tests/categories/test_session.py, tests/unit_tests/means_test/test_views_summary.py
- Adds functionality to get the users subcategory from the session
- Stores the users answer to the initial category question to the `CategoryAnswers` list as a new `CATEGORY` question type.
- Updates the 'Check your answers' page to use this new information rather than relying on the order of the Category Answers.
=> Get users' subcategory

app/main/__init__.py, app/main/middleware.py, tests/unit_tests/test_middleware.py
- Disallows search engine indexing by adding `X-Robots-Tag=noindex` to the response headers of all requests.
=> LGA-3479: Disallow search engine indexing

app/find_a_legal_adviser/routes.py, tests/unit_tests/find_a_legal_adviser/test_fala.py
- Handle no primary or secondary category selections correctly
- Updates the FALA unit tests
=> LGA-3663: Fix FALA not working when no category is selected

.github/workflows/test.yml, app/contact/forms.py, tests/functional_tests/contact/test_contact.py
Removes the validation from the postcode dropdown field so that it is not erroneously identified as empty by wtforms
=> LGA-3667 Repair Postcode Validation

app/contact/forms.py, app/contact/urls.py, app/contact/views.py, app/session.py, app/templates/categories/in-scope.html, tests/functional_tests/contact/test_confirmation.py, tests/unit_tests/contact/test_views.py
- Submits the users' scope traversal to CLA Backend
- Submits the users' financial eligibility status to CLA Backend
- Submits the users' notes to the new client notes field of `legalaid.Case`
- Fixes some erroneous whitespace around the "Contact CLA" link on the "In-scope" page
=> LGA-3544: Submit scope traversal details

app/categories/constants.py, tests/functional_tests/categories/send/test_send.py, tests/unit_tests/categories/test_session.py
- Fixes an issue where the user journey:
Help with a child or young person's SEND → Is this about a child who is or has been in care? → No
Was incorrectly classified as not in-scope.
- Updates a unit test that needs to reference and out-of-scope category
=> LGA-3669: Fix SEND session expired bug

app/config/__init__.py, tests/functional_tests/means_test/test_review.py, tests/functional_tests/test_header.py
- Updates the service name to "Check if you can get legal aid" to prevent confusion during manual testing
=> Update service name

helm_deploy/laa-access-civil-legal-aid/templates/ingress.yaml, helm_deploy/laa-access-civil-legal-aid/values.yaml, helm_deploy/laa-access-civil-legal-aid/values/values-dev.yaml, helm_deploy/laa-access-civil-legal-aid/values/values-production.yaml, helm_deploy/laa-access-civil-legal-aid/values/values-staging.yaml, helm_deploy/laa-access-civil-legal-aid/values/values-uat.yaml
- Switches the staging site to connect to the training CLA Backend environment, ahead of tomorrows testing
- Disables the whitelist on the beta site
=> Enable training backend connection and disable staging whitelist

app/means_test/forms/property.py
Updates the values field to allow for values in the millions. This was due to pence not being accounted for.
=> LGA-3675 Bug Property value fix

app/means_test/payload.py, tests/functional_tests/means_test/test_review.py
Changes the name of the val field referenced so that it can be passed into CHS.
=> LGA-3676 Child Benefit Field Fix

app/means_test/money_interval.py
Remembers 0 values if 0 values are entered instead of None.
=> LGA-3650 Remember 0 Values Bug

app/contact/views.py, tests/functional_tests/contact/test_contact.py, tests/unit_tests/contact/test_views.py
- Adds traversal protection to the contact us page.
https://github.com/user-attachments/assets/56a32863-3b11-4a5b-a10d-d910cca6f733
- Clears the users session on submitting the reasons for contacting form, as we do not want users to be able to submit the same case details multiple times.
=> LGA-3674: Fix being able to go back from the confirmation page

app/contact/views.py, tests/unit_tests/contact/test_views.py
- Fixes thirdparty emails failing to send due to mismatched form field keys.
=> Fix thirdparty emails failing to send

app/main/routes.py
- Set HTTPOnly to false on the cookies_policy cookie when set via the cookie page form.
This resolves an issue where this cookie could not be read by the client resulting in JavaScript failing to load.
=> Set HTTPOnly to false on the cookies_policy cookie

app/main/gtm.py, app/main/routes.py, app/static/src/js/headscripts/gtm.js
Amends the GTM anon ID so it updates to the datastream correctly. Also updates the expiry to 2 years (the browser maximum allowed expiry may reduce this).
=> Bug/LGA-3681 Repair GTM Anon ID

app/means_test/views.py, app/templates/contact/eligible.html, app/templates/means_test/components/progress-bar.html, app/templates/means_test/review.html, tests/functional_tests/means_test/test_progress.py, tests/unit_tests/means_test/test_form_progress.py, tests/unit_tests/means_test/test_form_submission.py
- Now the progress bar only allows you to navigate backwards and all forms need to be completed in order
- This page was previously missing this component
- If the user is deemed eligible/ ineligible without completing a page then the page will be appropriately removed from the progress component
https://github.com/user-attachments/assets/ec3bf338-4634-4be9-9031-3e5a288e820d
=> LGA-3692: Fix progress bar

app/config/__init__.py, app/main/__init__.py, app/templates/base.html
- Checks current time on each new request rather than during app startup so the rebrand will automatically be applied from the 25th of June 2025.
- Adds support for the `govuk-rebrand-enabled` query string, as was done for FALA.
=> LGA-3759: Fix rebrand not applying automatically
