ministryofjustice/laa-access-civil-legal-aid

.github/pull_request_template.md

- Adds the pull request template.

LGA-3082: Add default pull request template

---

.github/workflows/gajira.yml

Adds in jira ticket integration for the new access service

Add in gajira integration

---

.github/workflows/feature-branch.yml
.github/workflows/main-branch.yml
.github/workflows/scan-image.yml

LGA-3087 - Scan image with trivy

---

.github/workflows/feature-branch.yml
.github/workflows/main-branch.yml
.github/workflows/static-analysis.yml
sonar-project.properties

LGA-3084 - Add sonar cloud scanning

---

.github/workflows/build.yml
.github/workflows/feature-branch.yml

Add docker build cache during image build in the pipeline

LGA-3218 - Add docker build cache during image build in the pipeline

---

.trufflehog3.yml

Updates the trufflehog config to include app static.

Quick fix for trufflehog

---

.github/workflows/feature-branch.yml
.github/workflows/main-branch.yml

Update pipeline to include renamed trivy scan file.

Update pipeline to include renamed trivy scan file

---

app/categories/domestic_abuse/forms.py
app/categories/domestic_abuse/urls.py
app/categories/forms.py
app/categories/views.py
app/categories/widgets.py
tests/functional_tests/categories/domestic_abuse/test_domestic_abuse.py

LGA-3352 - Add safeguarding question

---

app/categories/__init__.py
app/categories/community_care/__init__.py
app/categories/community_care/urls.py
app/templates/categories/community_care/landing.html
app/templates/categories/housing/landing.html
app/templates/categories/index.html
tests/functional_tests/categories/community_care/test_community_care.py

Add care in the community category.

LGA-3343 - Add care in the community category

---

app/categories/__init__.py
app/categories/public/__init__.py
app/categories/public/forms.py
app/categories/public/urls.py
app/categories/views.py
app/templates/categories/components/cannot-find-your-problem.html
app/templates/categories/index.html
app/templates/categories/public/landing.html
app/templates/categories/public/reason.html
tests/functional_tests/categories/public/test_public.py

LGA-3371 - Add public category

---

app/categories/discrimination/forms.py
app/categories/views.py
app/categories/widgets.py
tests/functional_tests/categories/discrimination/test_discrimination.py

- Updates the "Why you were discriminated against" question to support multiple answers and route users appropriately

LGA 3373 Why were you treated differently

---

app/templates/categories/more-problems.html

- Updates the 'more problems covered by legal aid' to match the updated content and UI design record.
- Gives the page the correct title

LGA 3351: More problems covered by legal aid

---

app/static/src/scss/custom.scss
app/templates/categories/components/list-item.html
app/templates/categories/index.html
tests/functional_tests/categories/community_care/test_community_care.py
tests/functional_tests/categories/test_clinical_negilgence.py
tests/functional_tests/find_a_legal_adviser/test_categories.py

- Updates functional test to work with the new content

LGA 3368: Find problems covered by legal aid

---

app/categories/public/urls.py
app/templates/categories/index.html
app/templates/categories/public/landing.html
tests/functional_tests/categories/family/test_family.py
tests/functional_tests/categories/public/test_public.py

Updates the front door content to match the content record.

Fix front door content

---

.github/workflows/main-branch.yml

Repairs the main branch pipeline by including the env vars

Bug Fix Main Branch Pipeline

---

app/means_test/api.py
app/means_test/forms/__init__.py
app/means_test/forms/about_you.py
app/means_test/forms/benefits.py
app/means_test/views.py

Create a forms package for means test forms.

Create a forms package for means test forms

---

app/means_test/fields.py
app/means_test/forms/money.py
app/means_test/validators.py
app/templates/means_test/components/money-field.html
tests/unit_tests/conftest.py
tests/unit_tests/means_test/test_money_field.py

Move MoneyField into fields.py module
Rename CombinedTextWidget to MoneyFieldWidget
Rename CombinedTextField to MoneyField

Move MoneyField into the fields module

---

app/templates/categories/more-problems.html

- Update header to use XL on the more problems page

LGA-3528 Fix heading on more problems page

---

app/categories/mental_capacity/urls.py
tests/functional_tests/categories/mental_capacity/test_mental_capacity.py

- Updates mental capacity routing for social care

LGA-3530: Update social care routing

---

app/templates/categories/community_care/landing.html

- Removes unnecessary more problems text
- Updates cannot find your problem text

LGA-3527: Community care CLP

---

helm_deploy/laa-access-civil-legal-aid/templates/ingress.yaml

Disable WAF temporarily for ITHC testing, this is while we're not live.

disable waf temporarily, can rever this later

---

helm_deploy/laa-access-civil-legal-aid/templates/_helpers.tpl
helm_deploy/laa-access-civil-legal-aid/templates/ingress.yaml

Temporarily add static ip address. To delete IP later and to set enabled to "true" for Modsec post-ITHC as well.

temporarily add static ip and fix ingress modsec for ithc test 

---

.github/workflows/main-branch.yml

- Adds the UAT deployment to the release pipeline
This helps to ensure the UAT environment keeps in sync with our main environments.

Add UAT deployment to the release pipeline

---

app/means_test/forms/benefits.py
app/templates/means_test/additional-benefits.html

Add missing hint and descriptions for additional benefits form.

LGA-3484 - Add missing hint and descriptions for additional benefits form

---

app/templates/categories/in-scope.html

- Fixes an accessibility issue where heading levels were not correctly ordered.

Fix skipped heading levels on in-scope page

---

app/translations/cy/LC_MESSAGES/messages.po

Adds in the domestic abuse welsh translations to access.

LGA-3505: Welsh Translations - Domestic Abuse

---

app/means_test/forms/savings.py
tests/functional_tests/means_test/test_savings.py

- Add ValidateIfSession for savings and investments fields
- Add functional tests

Fix Savings Validators

---

helm_deploy/laa-access-civil-legal-aid/files/dashboard.json

Updates the grafana dashboard to include production monitoring.

Update Grafana Dashboard for Production Access Monitoring

---

app/categories/README.md
app/main/redirects.py

- Fixes a failing accessibility test due to an invalid route.

Rename invalid route

---

app/categories/constants.py
app/categories/family/urls.py

Redirect Family->Forced Marriage to Domestic abuse->Forced Marriage

BUG - Redirect Family->Forced Marriage to Domestic abuse->Forced Marriage

---

app/means_test/forms/property.py

Temporary fix for properties check your answers bug

---

app/api.py
tests/unit_tests/contact/test_contact.py

Fixes eligibility check not being correctly attached to cases

Fix eligibility check not being correctly attached to cases

---

app/categories/constants.py
app/categories/domestic_abuse/urls.py
app/categories/housing/urls.py
tests/functional_tests/categories/domestic_abuse/test_domestic_abuse.py

Updates the routing for problems with neighbours to housing instead of domestic abuse. Also updated tests.

LGA-3664 Problems with Neighbour Routing Fix

---

helm_deploy/laa-access-civil-legal-aid/values/values-staging.yaml

Revert training deployment

---

.github/workflows/feature-branch.yml
helm_deploy/laa-access-civil-legal-aid/values.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-dev.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-production.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-staging.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-uat.yaml

Setup routing cookie for new service.

Setup routing cookie for new service

---

.github/workflows/deploy-dev.yml
.github/workflows/feature-branch.yml
helm_deploy/laa-access-civil-legal-aid/templates/ingress.yaml
helm_deploy/laa-access-civil-legal-aid/values.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-dev.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-production.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-staging.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-uat.yaml

Add checklegalaid.service.gov.uk domains and subdomains to ingress hosts.

LGA-3679 - Add checklegalaid.service.gov.uk domains and subdomains to ingress hosts

---

.github/workflows/deploy-dev.yml

- Updates ingress host annotation in deploy-dev.yml

Fix dev deploy

---

app/categories/views.py
app/session.py
tests/functional_tests/categories/test_answer_change.py

Clears category answer if it is already defined on subcategory pages. Also adds tests.

LGA-3630 Changing answers should delete subsequent answers

---

app/means_test/forms/__init__.py
app/means_test/forms/property.py
app/means_test/views.py
tests/functional_tests/means_test/test_property.py

Displays properties on the review your answers page.

LGA-3673 Property Field Review your answers

---

app/static/src/scss/custom.scss
app/templates/base.html

Remove beta service badge for production.

LGA-3680 - Remove beta service badge for production

---

helm_deploy/laa-access-civil-legal-aid/values/values-production.yaml
helm_deploy/laa-access-civil-legal-aid/values/values-staging.yaml

Increase replica count to 4

---

app/config/__init__.py
app/main/routes.py
tests/unit_tests/test_pages.py

- Redirect header link to CLA GOV.UK main page.

Redirect header link to GOV.UK

---

app/categories/mixins.py
app/categories/views.py
app/contact/views.py
app/means_test/views.py

Send errors to sentry

---

app/contact/validators.py
tests/unit_tests/contact/test_contact.py

- Fixes callback validator KeyError when day selection is invalid
This resolves these Sentry errors:
- https://ministryofjustice.sentry.io/issues/6545644642/?alert_rule_id=15322489&alert_type=issue&environment=production&notification_uuid=09196745-b26c-486d-b363-c29da8527d6e&project=4507604981317632&referrer=slack
- https://ministryofjustice.sentry.io/issues/6545678188/?alert_rule_id=15322489&alert_type=issue&environment=production&notification_uuid=f545f94d-7265-41a2-8a57-89b52bd04903&project=4507604981317632&referrer=slack

Fix callback validator

---

helm_deploy/laa-access-civil-legal-aid/values/values-production.yaml

Sets the ingress of canary weight to 100 for Access

Production Canary to 100%

---

.github/workflows/test.yml
requirements/generated/requirements-development.txt
requirements/source/requirements-development.in

Adds pytest-xdist to allow the functional tests to run in parallel.

Run tests in parallel

---

Dockerfile
app/static/src/js/contact.js

Show BSL email field when main email field is emptied.

LGA-3643 - Show BSL email field when main email field is emptied

---

app/static/src/js/headscripts/gtm.js
app/templates/find_a_legal_adviser/results.html

Adds legacy GA4 functionality from CLA Public to Access, namely the Page load.

LGA-3472 Legacy GA4 Logic

---

app/templates/base.html

Add skip to exit this page GovUkSkip link.

LGA-3684 - Add skip to exit this page GovUkSkip link

---

app/main/routes.py
app/static/src/js/headscripts/gtm.js
tests/unit_tests/test_pages.py

Remove GA cookies after opting out on cookies page.

LGA-3683-Remove GA cookies after opting out on cookies page

---

app/categories/forms.py
app/main/__init__.py
app/session.py
app/templates/contact/contact.html
tests/functional_tests/categories/domestic_abuse/test_domestic_abuse.py

Changes the domestic abuse journey for when a user selects "No" on are you at immediate risk of harm to route straight to the contact us page.

LGA-3705 Bug - Update Domestic Abuse Journey

---

app/main/routes.py

Repairs the open redirect to allow blank referrers and removes any risks.

Quick fix for open redirect
